In [2]:
import numpy as np
import pandas as pd

In [4]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

## Working with dates

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [9]:
date['date']=pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [10]:
#Extract year
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
348 2019-02-09        1848       14     135       2019
759 2019-11-23        6534       14       4       2019
992 2019-11-01        4146        9       1       2019
29  2019-02-20         172        0       7       2019
502 2019-06-19        1232       14       8       2019

In [12]:
#Extract month no.
date['month_no']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  month_no
24  2019-07-24        2303       14     113       2019         7
521 2018-08-23        5482       25       7       2018         8
167 2019-07-30        5314       11      10       2019         7
891 2018-11-18        3904        1       9       2018        11
863 2019-03-14        3241       26       1       2019         3

In [14]:
#Extract month name
date['month_name']=date['date'].dt.month_name()
date.sample(5)

          date  product_id  city_id  orders  date_year  month_no month_name
220 2019-12-14        4482       28       2       2019        12   December
797 2019-03-17        4392       26       8       2019         3      March
715 2018-07-26        1667       25       9       2018         7       July
297 2019-12-02        5653       17       4       2019        12   December
450 2018-09-30        3532       25       5       2018         9  September

In [17]:
#Extract date name
date['date_day']=date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,month_no,month_name,date_day
878,2019-04-30,7510,16,5,2019,4,April,30
954,2019-06-21,7350,16,31,2019,6,June,21
253,2018-10-13,3793,22,32,2018,10,October,13
647,2018-09-05,6556,23,2,2018,9,September,5
904,2019-06-17,1828,0,1,2019,6,June,17

In [20]:
#Extract day of week
date['date_dow']=date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,month_no,month_name,date_day,date_dow
736,2018-12-23,1365,26,1,2018,12,December,23,6
348,2019-02-09,1848,14,135,2019,2,February,9,5
695,2018-10-01,7294,1,2,2018,10,October,1,0
424,2019-10-12,637,26,1,2019,10,October,12,5
944,2019-07-26,4439,2,24,2019,7,July,26,4

In [21]:
#Extract dow name
date['date_dow_name']=date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,month_no,month_name,date_day,date_dow,date_dow_name
118,2019-03-12,2251,9,1,2019,3,March,12,1,Tuesday
847,2019-08-17,6253,30,1,2019,8,August,17,5,Saturday
336,2018-11-30,4192,14,26,2018,11,November,30,4,Friday
823,2019-08-05,2864,18,1,2019,8,August,5,0,Monday
922,2019-03-28,1658,16,27,2019,3,March,28,3,Thursday

In [24]:
#Extract week of year
date['date_week']=date['date'].dt.isocalendar().week
date.sample(5)

,date,product_id,city_id,orders,date_year,month_no,month_name,date_day,date_dow,date_dow_name,date_week
982,2019-06-22,354,13,2,2019,6,June,22,5,Saturday,25
547,2019-06-21,793,29,3,2019,6,June,21,4,Friday,25
469,2019-11-15,5549,28,2,2019,11,November,15,4,Friday,46
622,2018-09-21,3234,25,2,2018,9,September,21,4,Friday,38
108,2019-10-24,7538,0,1,2019,10,October,24,3,Thursday,43

In [25]:
#Extract quarter of year
date['quarter']=date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_year,month_no,month_name,date_day,date_dow,date_dow_name,date_week,quarter
693,2019-07-26,2271,3,60,2019,7,July,26,4,Friday,30,3
215,2018-11-01,7266,19,4,2018,11,November,1,3,Thursday,44,4
927,2018-12-04,219,3,3,2018,12,December,4,1,Tuesday,49,4
616,2019-02-09,5733,25,2,2019,2,February,9,5,Saturday,6,1
855,2018-08-06,4809,14,1,2018,8,August,6,0,Monday,32,3

In [26]:
#Etract time elapsed between dates

import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 3, 23, 22, 17, 37, 101458)

In [27]:
today-date['date']

0     2295 days 22:17:37.101458
1     2777 days 22:17:37.101458
2     2708 days 22:17:37.101458
3     2410 days 22:17:37.101458
4     2633 days 22:17:37.101458
                 ...
995   2723 days 22:17:37.101458
996   2664 days 22:17:37.101458
997   2512 days 22:17:37.101458
998   2577 days 22:17:37.101458
999   2351 days 22:17:37.101458
Name: date, Length: 1000, dtype: timedelta64[ns]

In [28]:
(today-date['date']).dt.days

0      2295
1      2777
2      2708
3      2410
4      2633
       ...
995    2723
996    2664
997    2512
998    2577
999    2351
Name: date, Length: 1000, dtype: int64

## Time

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [31]:
time['date']=pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [32]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [33]:
time['time']=time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time differences in month,hour,etc

In [37]:
#month passed
(today-date['date'])/np.timedelta64(1,'D')/30

0      76.530963
1      92.597630
2      90.297630
3      80.364297
4      87.797630
         ...
995    90.797630
996    88.830963
997    83.764297
998    85.930963
999    78.397630
Name: date, Length: 1000, dtype: float64

In [38]:
#minutes passed
(today-time['date'])/np.timedelta64(1,'m')

0      6.453928e+06
1      6.258158e+06
2      6.957957e+06
3      5.952827e+06
4      6.524587e+06
           ...
995    7.374088e+06
996    6.396424e+06
997    7.066001e+06
998    7.233044e+06
999    6.184733e+06
Name: date, Length: 1000, dtype: float64

In [39]:
#hours passed
(today-time['date'])/np.timedelta64(1,'h')

0      107565.460306
1      104302.626973
2      115965.943639
3       99213.776973
4      108743.110306
           ...
995    122901.460306
996    106607.060306
997    117766.676973
998    120550.726973
999    103078.876973
Name: date, Length: 1000, dtype: float64